Config = {}

Config.marketitems = {
    ["General"] = {
        { ["name"] = "Tosti", ["price"] = 2, ["amount"] = 50, ["image"] = "tosti.png", ["itemname"] = "tosti" },
        { ["name"] = "Lighter", ["price"] = 2, ["amount"] = 50, ["image"] = "lighter.png", ["itemname"] = "lighter" },
        { ["name"] = "Rolling Paper", ["price"] = 2, ["amount"] = 5000, ["image"] = "rolling_paper.png", ["itemname"] = "rolling_paper" },
    },
    ["Foods"] = {
        { ["name"] = "Sandwich", ["price"] = 2, ["amount"] = 50, ["image"] = "sandwich.png", ["itemname"] = "sandwich" },
        { ["name"] = "Egg Sandwich", ["price"] = 5, ["amount"] = 10, ["image"] = "eggsandwich.png", ["itemname"] = "eggsandwich" },
        { ["name"] = "Tuna Sandwich", ["price"] = 4, ["amount"] = 10, ["image"] = "tunasandwich.png", ["itemname"] = "tunasandwich" },
    },
    ["Drinks"] = {
        { ["name"] = "Water Bottle", ["price"] = 2, ["amount"] = 50, ["image"] = "water_bottle.png", ["itemname"] = "water_bottle" },
        { ["name"] = "Beer", ["price"] = 7, ["amount"] = 50, ["image"] = "beer.png", ["itemname"] = "beer" },
        { ["name"] = "Whiskey", ["price"] = 10, ["amount"] = 50, ["image"] = "whiskey.png", ["itemname"] = "whiskey" },
        { ["name"] = "Vodka", ["price"] = 12, ["amount"] = 50, ["image"] = "vodka.png", ["itemname"] = "vodka" },
    },
    ["Others"] = {
        { ["name"] = "Bandage", ["price"] = 100, ["amount"] = 50, ["image"] = "bandage.png", ["itemname"] = "bandage" },
    },
}

Config.hardwareitems = {
    ["General"] = {
        { ["name"] = "Skateboard", ["price"] = 300, ["amount"] = 10, ["type"] = "item", ["image"] = "skateboard.png", ["itemname"] = "skateboard" },
        { ["name"] = "License plate", ["price"] = 1230, ["amount"] = 10, ["type"] = "item", ["image"] = "plate.png", ["itemname"] = "licenseplate" },
        { ["name"] = "RC Car", ["price"] = 230, ["amount"] = 50, ["type"] = "item", ["image"] = "rccar.png", ["itemname"] = "rccar" },
        { ["name"] = "Binoculars", ["price"] = 50, ["amount"] = 50, ["type"] = "item", ["image"] = "binoculars.png", ["itemname"] = "binoculars" },
        { ["name"] = "Firework 1", ["price"] = 50, ["amount"] = 50, ["type"] = "item", ["image"] = "firework1.png", ["itemname"] = "firework1" },
        { ["name"] = "Firework 2", ["price"] = 50, ["amount"] = 50, ["type"] = "item", ["image"] = "firework2.png", ["itemname"] = "firework2" },
        { ["name"] = "Firework 3", ["price"] = 50, ["amount"] = 50, ["type"] = "item", ["image"] = "firework3.png", ["itemname"] = "firework3" },
        { ["name"] = "Firework 4", ["price"] = 50, ["amount"] = 50, ["type"] = "item", ["image"] = "firework4.png", ["itemname"] = "firework4" },
        { ["name"] = "Cleaning Kit", ["price"] = 150, ["amount"] = 150, ["type"] = "item", ["image"] = "cleaningkit.png", ["itemname"] = "cleaningkit" },
        { ["name"] = "Advanced Repair Kit", ["price"] = 500, ["amount"] = 50, ["type"] = "item", ["image"] = "advancedrepairkit.png", ["itemname"] = "advancedrepairkit" },
        { ["name"] = "Lockpick", ["price"] = 200, ["amount"] = 50, ["type"] = "item", ["image"] = "lockpick.png", ["itemname"] = "lockpick" },
        { ["name"] = "Weapon Wrench", ["price"] = 250, ["amount"] = 250, ["type"] = "item", ["image"] = "weapon_wrench.png", ["itemname"] = "weapon_wrench" },
        { ["name"] = "Weapon Hammer", ["price"] = 250, ["amount"] = 250, ["type"] = "item", ["image"] = "weapon_hammer.png", ["itemname"] = "weapon_hammer" },
        { ["name"] = "Notebook", ["price"] = 10, ["amount"] = 250, ["type"] = "item", ["image"] = "notebook.png", ["itemname"] = "notebook" },

    },
    ["Communication"] = {
        { ["name"] = "Phone", ["price"] = 850, ["amount"] = 50, ["type"] = "item", ["image"] = "phone.png", ["itemname"] = "phone" },
        { ["name"] = "Radio", ["price"] = 250, ["amount"] = 50, ["type"] = "item", ["image"] = "radio.png", ["itemname"] = "radio" },
    },
    ["Drones"] = {
        { ["name"] = "B Drone", ["price"] = 399, ["amount"] = 1, ["type"] = "item", ["image"] = "drones.png", ["itemname"] = "bdrone" },
        { ["name"] = "Bad Drone", ["price"] = 499, ["amount"] = 1, ["type"] = "item", ["image"] = "drones.png", ["itemname"] = "baddrone" },
        { ["name"] = "BB Drone", ["price"] = 599, ["amount"] = 5, ["type"] = "item", ["image"] = "drones.png", ["itemname"] = "bbdrone" },
        { ["name"] = "BC Drone", ["price"] = 699, ["amount"] = 5, ["type"] = "item", ["image"] = "drones.png", ["itemname"] = "bcdrone" },
        { ["name"] = "BD Drone", ["price"] = 756, ["amount"] = 2, ["type"] = "item", ["image"] = "drones.png", ["itemname"] = "bddrone" },
    },
}

Config.weaponshopitems = {
    ["General"] = {
        { ["name"] = "Weapon Knife", ["price"] = 230, ["amount"] = 50, ["type"] = "item", ["image"] = "weapon_knife.png", ["itemname"] = "weapon_knife" },
        { ["name"] = "Weapon Bat", ["price"] = 250, ["amount"] = 250, ["type"] = "item", ["image"] = "weapon_bat.png", ["itemname"] = "weapon_bat" },
        { ["name"] = "Weapon Hatchet", ["price"] = 250, ["amount"] = 250, ["type"] = "item", ["image"] = "weapon_hatchet.png", ["itemname"] = "weapon_hatchet" },
    },
    ["Firearms"] = {
        { ["name"] = "Weapon Pistol", ["price"] = 2500, ["amount"] = 5, ["type"] = "item", ["image"] = "weapon_pistol.png", ["itemname"] = "weapon_pistol" },
        { ["name"] = "Weapon SNS Pistol", ["price"] = 1500, ["amount"] = 5, ["type"] = "item", ["image"] = "weapon_snspistol.png", ["itemname"] = "weapon_snspistol" },
        { ["name"] = "Weapon Vintage Pistol", ["price"] = 4000, ["amount"] = 5, ["type"] = "item", ["image"] = "weapon_vintagepistol.png", ["itemname"] = "weapon_vintagepistol" },
    },
    ["Ammunition"] = {
        { ["name"] = "Pistol Ammo", ["price"] = 250, ["amount"] = 250, ["type"] = "item", ["image"] = "pistol_ammo.png", ["itemname"] = "pistol_ammo" },
    },
}

Config.weedshopitems = {
    ["General"] = {
        { ["name"] = "Joint", ["price"] = 10, ["amount"] = 50, ["type"] = "item", ["image"] = "joint.png", ["itemname"] = "joint" },
        { ["name"] = "Weapon poolcue", ["price"] = 100, ["amount"] = 50, ["type"] = "item", ["image"] = "weapon_poolcue.png", ["itemname"] = "weapon_poolcue" },
        { ["name"] = "Weed nutrition", ["price"] = 20, ["amount"] = 50, ["type"] = "item", ["image"] = "weed_nutrition.png", ["itemname"] = "weed_nutrition" },
        { ["name"] = "Empty weed bag", ["price"] = 2, ["amount"] = 1000, ["type"] = "item", ["image"] = "empty_weed_bag.png", ["itemname"] = "empty_weed_bag" },
        { ["name"] = "Rolling Paper", ["price"] = 2, ["amount"] = 1000, ["type"] = "item", ["image"] = "rolling_paper.png", ["itemname"] = "rolling_paper" },
    },
    ["Weed"] = {
        { ["name"] = "fertilizer", ["price"] = 10, ["amount"] = 200, ["type"] = "item", ["image"] = "fertilizer.png", ["itemname"] = "fertilizer" },
        { ["name"] = "dust", ["price"] = 5, ["amount"] = 200, ["type"] = "item", ["image"] = "dust.png", ["itemname"] = "dust" },
        { ["name"] = "weed_seed", ["price"] = 15, ["amount"] = 200, ["type"] = "item", ["image"] = "weed_seed.png", ["itemname"] = "weed_seed" },
        { ["name"] = "water", ["price"] = 2, ["amount"] = 200, ["type"] = "item", ["image"] = "water.png", ["itemname"] = "water" },
    },
}
Config.digital = {
    ["crypto"] = {
        { ["name"] = "shitgpu", ["price"] = 50, ["amount"] = 10, ["type"] = "item", ["image"] = "shitgpu.png", ["itemname"] = "shitgpu" },
        { ["name"] = "1050gpu", ["price"] = 100, ["amount"] = 10, ["type"] = "item", ["image"] = "1050.png", ["itemname"] = "1050gpu" },
        { ["name"] = "1060gpu", ["price"] = 200, ["amount"] = 10, ["type"] = "item", ["image"] = "1060.png", ["itemname"] = "1060gpu" },
        { ["name"] = "1080gpu", ["price"] = 300, ["amount"] = 10, ["type"] = "item", ["image"] = "1080.png", ["itemname"] = "1080gpu" },
        { ["name"] = "2080gpu", ["price"] = 400, ["amount"] = 10, ["type"] = "item", ["image"] = "2080.png", ["itemname"] = "2080gpu" },
        { ["name"] = "3060gpu", ["price"] = 500, ["amount"] = 10, ["type"] = "item", ["image"] = "3060.png", ["itemname"] = "3060gpu" },
        { ["name"] = "4090gpu", ["price"] = 600, ["amount"] = 10, ["type"] = "item", ["image"] = "4090.png", ["itemname"] = "4090gpu" },
        { ["name"] = "thermalpast", ["price"] = 20, ["amount"] = 100, ["type"] = "item", ["image"] = "thermalpast.png", ["itemname"] = "thermalpast" },        
    },
    ["phone"] = {
        { ["name"] = "tablet", ["price"] = 1000, ["amount"] = 5, ["type"] = "item", ["image"] = "tablet.png", ["itemname"] = "tablet" },
        { ["name"] = "phone", ["price"] = 500, ["amount"] = 10, ["type"] = "item", ["image"] = "phone.png", ["itemname"] = "phone" },
        { ["name"] = "radio", ["price"] = 300, ["amount"] = 15, ["type"] = "item", ["image"] = "radio.png", ["itemname"] = "radio" },
    },
}
Config.containers = {
    ["Containers"] = {
        { ["name"] = "Small Green Container", ["price"] = 100, ["amount"] = 1, ["type"] = "item", ["image"] = "container_green_small.png", ["itemname"] = "containergreensmall" },
        { ["name"] = "Mid Blue Container", ["price"] = 200, ["amount"] = 1, ["type"] = "item", ["image"] = "container_blue_mid.png", ["itemname"] = "containerbluemid" },
        { ["name"] = "Mid Old Container", ["price"] = 150, ["amount"] = 1, ["type"] = "item", ["image"] = "container_old_mid.png", ["itemname"] = "containeroldmid" },
        { ["name"] = "Mid White Container", ["price"] = 180, ["amount"] = 1, ["type"] = "item", ["image"] = "container_white_mid.png", ["itemname"] = "containerwhitemid" },
        { ["name"] = "Boltcutter", ["price"] = 75, ["amount"] = 1, ["type"] = "item", ["image"] = "boltcutter.png", ["itemname"] = "containerboltcutter" },
    },

    
}   
Config.comics = {
    ["Toys"] = {
        { ["name"] = "Monkey", ["price"] = 100, ["amount"] = 1, ["type"] = "item", ["image"] = "monky.png", ["itemname"] = "monky" },
        { ["name"] = "Shark Boi", ["price"] = 250, ["amount"] = 1, ["type"] = "item", ["image"] = "shark_boi.png", ["itemname"] = "shark_boi" },
        { ["name"] = "Monkey Punk", ["price"] = 150, ["amount"] = 1, ["type"] = "item", ["image"] = "monkey_punk.png", ["itemname"] = "monkey_punk" },
        { ["name"] = "Fox", ["price"] = 180, ["amount"] = 1, ["type"] = "item", ["image"] = "fox.png", ["itemname"] = "fox" },
        { ["name"] = "Quest Mouse", ["price"] = 200, ["amount"] = 1, ["type"] = "item", ["image"] = "questing_mouse.png", ["itemname"] = "questing_mouse" },
        { ["name"] = "Armored Cat", ["price"] = 220, ["amount"] = 1, ["type"] = "item", ["image"] = "armored_cat.png", ["itemname"] = "armored_cat" },
        { ["name"] = "Hollow Knight", ["price"] = 240, ["amount"] = 1, ["type"] = "item", ["image"] = "hollow_knight.png", ["itemname"] = "hollow_knight" },
        { ["name"] = "Knight Cat", ["price"] = 230, ["amount"] = 1, ["type"] = "item", ["image"] = "knight_cat.png", ["itemname"] = "knight_cat" },
        { ["name"] = "Dino", ["price"] = 170, ["amount"] = 1, ["type"] = "item", ["image"] = "dino.png", ["itemname"] = "dino" },
        { ["name"] = "Dino Student", ["price"] = 170, ["amount"] = 1, ["type"] = "item", ["image"] = "dino_student.png", ["itemname"] = "dino_student" },
        { ["name"] = "Angel Pig", ["price"] = 200, ["amount"] = 1, ["type"] = "item", ["image"] = "pig_angel.png", ["itemname"] = "pig_angel" },
        { ["name"] = "Mickey Mouse", ["price"] = 250, ["amount"] = 1, ["type"] = "item", ["image"] = "mickey_mouse.png", ["itemname"] = "mickey_mouse" },
        { ["name"] = "Blossom", ["price"] = 180, ["amount"] = 1, ["type"] = "item", ["image"] = "blossom.png", ["itemname"] = "blossom" },
        { ["name"] = "Buttercup", ["price"] = 180, ["amount"] = 1, ["type"] = "item", ["image"] = "buttercup.png", ["itemname"] = "buttercup" },
        { ["name"] = "Bubbles", ["price"] = 180, ["amount"] = 1, ["type"] = "item", ["image"] = "bubbles.png", ["itemname"] = "bubbles" },
    
    },
    ["cards"] = {
        { ["name"] = "Golden Egg", ["price"] = 1000, ["amount"] = 50, ["image"] = "goldenegg.png", ["itemname"] = "goldenegg" },
        { ["name"] = "Toy Chest", ["price"] = 10000, ["amount"] = 50, ["image"] = "toychest.png", ["itemname"] = "toychest" },
        { ["name"] = "Booster Box", ["price"] = 10000, ["amount"] = 50, ["image"] = "boosterbox.png", ["itemname"] = "boosterbox" },
        { ["name"] = "Booster Pack", ["price"] = 1000, ["amount"] = 50, ["image"] = "boosterpack.png", ["itemname"] = "boosterpack" },
        { ["name"] = "Card Binder", ["price"] = 10000, ["amount"] = 50, ["image"] = "binder.png", ["itemname"] = "binder" },
    },
  
}   
Config.pets = {
    ["pets"] = {
        { ["name"] = "Westy Companion", ["price"] = 50000, ["amount"] = 5, ["image"] = "A_C_Westy.png", ["itemname"] = "keepcompanionwesty" },
        { ["name"] = "Shepherd Companion", ["price"] = 150000, ["amount"] = 5, ["image"] = "A_C_shepherd.png", ["itemname"] = "keepcompanionshepherd" },
        { ["name"] = "Retriever Companion", ["price"] = 50000, ["amount"] = 5, ["image"] = "A_C_Retriever.png", ["itemname"] = "keepcompanionretriever" },
        { ["name"] = "Rottweiler Companion", ["price"] = 75000, ["amount"] = 5, ["image"] = "A_Rottweiler.png", ["itemname"] = "keepcompanionrottweiler" },
        { ["name"] = "Pug Companion", ["price"] = 95000, ["amount"] = 5, ["image"] = "A_C_Pug.png", ["itemname"] = "keepcompanionpug" },
        { ["name"] = "Poodle Companion", ["price"] = 50000, ["amount"] = 5, ["image"] = "A_C_Poodle.png", ["itemname"] = "keepcompanionpoodle" },
        { ["name"] = "Mountain Lion Companion", ["price"] = 50000, ["amount"] = 5, ["image"] = "A_C_MtLion.png", ["itemname"] = "keepcompanionmtlion2" },
        { ["name"] = "Cat Companion", ["price"] = 50000, ["amount"] = 5, ["image"] = "A_C_Cat_01.png", ["itemname"] = "keepcompanioncat" },
        { ["name"] = "Husky Companion", ["price"] = 50000, ["amount"] = 5, ["image"] = "A_C_Husky.png", ["itemname"] = "keepcompanionhusky" },
        { ["name"] = "Rabbit Companion", ["price"] = 15000, ["amount"] = 50, ["image"] = "A_C_Rabbit_01.png", ["itemname"] = "keepcompanionrabbit" },
        { ["name"] = "Hen Companion", ["price"] = 5000, ["amount"] = 50, ["image"] = "A_C_Hen.png", ["itemname"] = "keepcompanionhen" },
        { ["name"] = "Coyote Companion", ["price"] = 50000, ["amount"] = 50, ["image"] = "A_C_Coyote.png", ["itemname"] = "keepcompanioncoyote" },               
  },
  ["accessories"] = {
    { ["name"] = "Pet Food", ["price"] = 500, ["amount"] = 1000, ["image"] = "petfood.png", ["itemname"] = "petfood" },
    { ["name"] = "Pet Collar", ["price"] = 50000, ["amount"] = 50, ["image"] = "collarpet.png", ["itemname"] = "collarpet" },
    { ["name"] = "Pet First Aid Kit", ["price"] = 5000, ["amount"] = 50, ["image"] = "firstaidforpet.png", ["itemname"] = "firstaidforpet" },
    { ["name"] = "Pet Name Tag", ["price"] = 5000, ["amount"] = 50, ["image"] = "petnametag.png", ["itemname"] = "petnametag" },
    { ["name"] = "Portable Pet Water Bottle", ["price"] = 5000, ["amount"] = 50, ["image"] = "petwaterbottleportable.png", ["itemname"] = "petwaterbottleportable" },
    { ["name"] = "Pet Grooming Kit", ["price"] = 5000, ["amount"] = 50, ["image"] = "petgroomingkit.png", ["itemname"] = "petgroomingkit" },            
},
    
}   


Config.Locations = {
    [1] = {
        ["name"] = "24/7 Supermarket",
        ["category"] = "24/7 Supermarket",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["radius"] = 1.5,
        ["coords"] = vector4(28.4572, -1341.5784, 29.4942, 171.4473),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },   
    [2] = {
        ["name"] = "24/7 Supermarket",
        ["category"] = "24/7 Supermarket",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["radius"] = 1.5,
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["coords"] = vector4(-3045.8318, 586.7306, 7.9064, 280.5797),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },   
    [3] = {
        ["name"] = "24/7 Supermarket",
        ["category"] = "24/7 Supermarket",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["radius"] = 1.5,
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["coords"] = vector4(-3247.7271, 1004.6028, 12.8281, 258.3035),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },   
    [4] = {
        ["name"] = "24/7 Supermarket",
        ["category"] = "24/7 Supermarket",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["radius"] = 1.5,
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["coords"] = vector4(1734.0781, 6418.5552, 35.0345, 150.3757),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },   
    [5] = {
        ["name"] = "24/7 Supermarket",
        ["category"] = "24/7 Supermarket",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["radius"] = 1.5,
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["coords"] = vector4(1960.8323, 3746.9939, 32.3408, 199.3820),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },   
    [6] = {
        ["name"] = "24/7 Supermarket",
        ["category"] = "24/7 Supermarket",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["radius"] = 1.5,
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["coords"] = vector4(545.8725, 2665.1125, 42.1537, 8.7354),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },   
    [7] = {
        ["name"] = "24/7 Supermarket",
        ["category"] = "24/7 Supermarket",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["radius"] = 1.5,
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["coords"] = vector4(2674.8005, 3285.5076, 55.2384, 252.8320),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },   
    [8] = {
        ["name"] = "24/7 Supermarket",
        ["category"] = "24/7 Supermarket",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["radius"] = 1.5,
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["coords"] = vector4(2551.6050, 385.0165, 108.6202, 279.8845),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },  
    [9] = {
        ["name"] = "24/7 Supermarket",
        ["category"] = "24/7 Supermarket",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["radius"] = 1.5,
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["coords"] = vector4(377.7897, 331.0955, 103.5637, 162.7169),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },    

    [10] = {
        ["name"] = "Hardware",
        ["category"] = "Hardware",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["radius"] = 1.5,
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["coords"] = vector4(45.68, -1749.04, 29.61, 53.13),
        ["categoryList"] = {
            ["General"] = "Security and maintenance.",
            ["Communication"] = "Phones and radios for communication.",
            ["Drones"] = "Various types of drones.",
        --    ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.hardwareitems,
    },
    [11] = {
        ["name"] = "Hardware",
        ["category"] = "Hardware",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["coords"] = vector4(2747.71, 3472.85, 55.67, 255.08),
        ["categoryList"] = {
            ["General"] = "Security and maintenance.",
            ["Communication"] = "Phones and radios for communication.",
            ["Drones"] = "Various types of drones.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.hardwareitems,
    },
    [12] = {
        ["name"] = "Hardware",
        ["category"] = "Hardware",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["coords"] = vector4(-421.83, 6136.13, 31.88, 228.2),
        ["categoryList"] = {
            ["General"] = "Security and maintenance.",
            ["Communication"] = "Phones and radios for communication.",
            ["Drones"] = "Various types of drones.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.hardwareitems,
    },

    [13] = {
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["coords"] = vector4(-661.96, -933.53, 21.83, 177.05),
        ["categoryList"] = {
            ["General"] = "Close-range combat weapons.",
            ["Firearms"] = "Ranged weapons using bullets.",
            ["Ammunition"] = "Ammo for firearms.",
        },
        ["itemList"] = Config.weaponshopitems,
    },

    [14] = {
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["coords"] = vector4(809.68, -2159.13, 29.62, 1.43),
        ["categoryList"] = {
            ["General"] = "Close-range combat weapons.",
            ["Firearms"] = "Ranged weapons using bullets.",
            ["Ammunition"] = "Ammo for firearms.",
        },
        ["itemList"] = Config.weaponshopitems,
    },
    [15] = {
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["coords"] = vector4(1692.67, 3761.38, 34.71, 227.65),
        ["categoryList"] = {
            ["General"] = "Close-range combat weapons.",
            ["Firearms"] = "Ranged weapons using bullets.",
            ["Ammunition"] = "Ammo for firearms.",
        },
        ["itemList"] = Config.weaponshopitems,
    },
    [16] = {
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["coords"] = vector4(-331.23, 6085.37, 31.45, 228.02),
        ["categoryList"] = {
            ["General"] = "Close-range combat weapons.",
            ["Firearms"] = "Ranged weapons using bullets.",
            ["Ammunition"] = "Ammo for firearms.",
        },
        ["itemList"] = Config.weaponshopitems,
    },
    [17] = {
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["coords"] = vector4(253.63, -51.02, 69.94, 72.91),
        ["categoryList"] = {
            ["General"] = "Close-range combat weapons.",
            ["Firearms"] = "Ranged weapons using bullets.",
            ["Ammunition"] = "Ammo for firearms.",
        },
        ["itemList"] = Config.weaponshopitems,
    },
    [18] = {
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["coords"] = vector4(23.0, -1105.67, 29.8, 162.91),
        ["categoryList"] = {
            ["General"] = "Close-range combat weapons.",
            ["Firearms"] = "Ranged weapons using bullets.",
            ["Ammunition"] = "Ammo for firearms.",
        },
        ["itemList"] = Config.weaponshopitems,
    },
    [19] = {
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["coords"] = vector4(2567.48, 292.59, 108.73, 349.68),
        ["categoryList"] = {
            ["General"] = "Close-range combat weapons.",
            ["Firearms"] = "Ranged weapons using bullets.",
            ["Ammunition"] = "Ammo for firearms.",
        },
        ["itemList"] = Config.weaponshopitems,
    },
    [20] = {
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["coords"] = vector4(-1118.59, 2700.05, 18.55, 221.89),
        ["categoryList"] = {
            ["General"] = "Close-range combat weapons.",
            ["Firearms"] = "Ranged weapons using bullets.",
            ["Ammunition"] = "Ammo for firearms.",
        },
        ["itemList"] = Config.weaponshopitems,
    },
    [21] = {
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["coords"] = vector4(841.92, -1035.32, 28.19, 1.56),
        ["categoryList"] = {
            ["General"] = "Close-range combat weapons.",
            ["Firearms"] = "Ranged weapons using bullets.",
            ["Ammunition"] = "Ammo for firearms.",
        },
        ["itemList"] = Config.weaponshopitems,
    },
    [22] = {
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["coords"] = vector4(-1304.19, -395.12, 36.7, 75.03),
        ["categoryList"] = {
            ["General"] = "Close-range combat weapons.",
            ["Firearms"] = "Ranged weapons using bullets.",
            ["Ammunition"] = "Ammo for firearms.",
        },
        ["itemList"] = Config.weaponshopitems,
    },
    [23] = {
        ["name"] = "Weapon Shop",
        ["category"] = "Weapon",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["coords"] = vector4(-3173.31, 1088.85, 20.84, 244.18),
        ["categoryList"] = {
            ["General"] = "Close-range combat weapons.",
            ["Firearms"] = "Ranged weapons using bullets.",
            ["Ammunition"] = "Ammo for firearms.",
        },
        ["itemList"] = Config.weaponshopitems,
    },
    [24] = {
        ["name"] = "LTD Gasoline",
        ["category"] = "LTD",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["coords"] = vector4(-47.02, -1758.23, 29.42, 45.05),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },       
    [25] = {
        ["name"] = "LTD Gasoline",
        ["category"] = "LTD",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["coords"] = vector4(-706.06, -913.97, 19.22, 88.04),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },    
    [26] = {
        ["name"] = "LTD Gasoline",
        ["category"] = "LTD",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["coords"] = vector4(-1820.02, 794.03, 138.09, 135.45),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },  
    [27] = {
        ["name"] = "LTD Gasoline",
        ["category"] = "LTD",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["coords"] = vector4(1164.71, -322.94, 69.21, 101.72),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },
    [28] = {
        ["name"] = "LTD Gasoline",
        ["category"] = "LTD",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["coords"] = vector4(1697.87, 4922.96, 42.06, 324.71),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },
    [29] = {
        ["name"] = "Smoke On The Water",
        ["category"] = "Enjoy :)",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 140,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["ped"] = 'a_m_y_hippy_01',
        ["scenario"] = "WORLD_HUMAN_AA_SMOKE",
        ["radius"] = 1.5,
        ["coords"] = vector4(-1168.26, -1573.2, 4.66, 105.24),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Weed"] = "Weed shop items.",
        },
        ["itemList"] = Config.weedshopitems,
    },    
    [30] = {
        ["name"] = "Containers store",
        ["category"] = "Containers",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["ped"] = 'a_m_y_yoga_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["coords"] = vector4(1202.7284, -1367.4825, 35.3769, 168.7791),
        ["categoryList"] = {
            ["Containers"] = "Store your objects",
        },
        ["itemList"] = Config.containers,
    },
    [31] = {
        ["name"] = "24/7 Supermarket",
        ["category"] = "24/7 Supermarket",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.7,
        ["blipcolor"] = 0,
        ["ped"] = 'mp_m_shopkeep_01',
        ["radius"] = 1.5,
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["coords"] = vector4(188.7782, -888.9073, 30.7131, 244.4121),
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Foods"] = "Foods for your hunger.",
            ["Drinks"] = "Drinks for your thirst.",
            ["Others"] = "Other items for your needs.",
        },
        ["itemList"] = Config.marketitems,
    },        
    [32] = {
        ["name"] = "Comics store",
        ["category"] = "Comics store",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 280,
        ["blipscale"] = 0.7,
        ["blipcolor"] = 4,
        ["ped"] = 'u_m_y_imporage',
        ["radius"] = 1.5,
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["coords"] = vector4(-140.2268, 224.1416, 94.9820, 85.9269),
        ["categoryList"] = {
            ["Toys"] = "Toys to play",
        },
        ["itemList"] = Config.comics,
    },  
    [33] = {
        ["name"] = "Computer store",
        ["category"] = "Computer store",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 280,
        ["blipscale"] = 0.7,
        ["blipcolor"] = 4,
        ["ped"] = 'a_m_y_yoga_01',
        ["radius"] = 1.5,
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["coords"] = vector4(-1530.4489, -402.4124, 35.6353, 230.4899),
        ["categoryList"] = {
            ["phone"] = "Phones and tablets",
            ["crypto"] = "GPU and more",
        },
        ["itemList"] = Config.digital,
    },  
    [34] = {
        ["name"] = "Pet Shop",
        ["category"] = "Pet Shop",
        ["job"] = "",
        ["showblip"] = true,
        ["blipsprite"] = 267,
        ["blipscale"] = 0.7,
        ["blipcolor"] = 5,
        ["ped"] = 'S_M_M_StrVend_01',
        ["radius"] = 1.5,
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["coords"] = vector4(561.18, 2741.51, 42.87, 199.08),
        ["categoryList"] = {
            ["pets"] = "Adopt your pet",
            ["accessories"] = "Everything you need for your pet",
        },
        ["itemList"] = Config.pets,
    },      

}

Config.Framework = "QBCore" -- QBCore or ESX or OLDQBCore -- NewESX

function Config.Error(cb)
    if Config.Framework == "ESX"  then
        TriggerClientEvent('esx:showNotification', source, 'You do not have sufficient funds.')
    elseif Config.Framework == "NewESX" then
        TriggerClientEvent('esx:showNotification', source, 'You do not have sufficient funds.')
    elseif Config.Framework == "QBCore" then
        TriggerClientEvent('QBCore:Notify', source, 'You do not have sufficient funds.', 'error', 5000)
    elseif Config.Framework == "OLDQBCore" then
        TriggerClientEvent('QBCore:Notify', source, 'You do not have sufficient funds.', 'error', 5000)
    else
        print(Config.Framework)
        print("Error: Unrecognized framework selected.")
    end
end

function Config.Success()
    if Config.Framework == "ESX"then
        TriggerClientEvent('esx:showNotification', source, 'Purchase transConfigtion successful.', 'success')
    elseif Config.Framework == "NewESX" then 
        TriggerClientEvent('esx:showNotification', source, 'Purchase transConfigtion successful.', 'success')
    elseif Config.Framework == "QBCore" then
        TriggerClientEvent('QBCore:Notify', source, 'Purchase transConfigtion successful.', 'success', 5000)
    elseif  Config.Framework == "OLDQBCore" then
        TriggerClientEvent('QBCore:Notify', source, 'Purchase transConfigtion successful.', 'success', 5000)
    else
        print(Config.Framework)
        print("Error: Unrecognized framework selected.")
    end
end
